name: flutter_data_graph
description: "Interactive numeric line charts for Flutter Web using Dygraph.js with a Flutter-friendly API."
repository: "https://github.com/capow20/flutter_data_graph"
version: 0.1.0

topics: 
  - chart
  - line-chart
  - graph
  - visualization
  - data-visualization

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  uuid: ^4.5.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3

flutter:
  assets:
    - lib/src/js/